version: '3.7'

services:
  butler-db:
    container_name: butler-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-release-butler
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  auth-db:
    container_name: butler-auth-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-detector-auth
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - auth-network
    volumes:
      - type: volume
        source: auth-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  auth-app:
    container_name: butler-auth-app
    image: metaldetector/metal-detector-auth
    environment:
      SERVER_PORT: 9000
      DATASOURCE_URL: jdbc:postgresql://auth-db:5432/metal-detector-auth
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: secret
      AUTHORIZATION_SERVER_PRIVATE_KEY:
      AUTHORIZATION_SERVER_PUBLIC_KEY:
      METAL_DETECTOR_USER_CLIENT_ID: metal-detector-user
      METAL_DETECTOR_USER_CLIENT_SECRET: userSecret
      METAL_DETECTOR_ADMIN_CLIENT_ID: metal-detector-admin
      METAL_DETECTOR_ADMIN_CLIENT_SECRET: adminSecret
    networks:
      - auth-network
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  butler-db-volume:
    name: butler-db
  auth-db-volume:
    name: butler-auth-db

networks:
  butler-network:
    name: butler-network
  auth-network:
    name: auth-network
