version: '3.7'

services:
  butler-db:
    container_name: butler-db
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/butler_db_root_password
      MYSQL_DATABASE: metal-release-butler
    secrets:
      - butler_db_root_password
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/mysql
    ports:
      - 3307:3306
    restart: always

  butler-phpmyadmin:
    container_name: butler-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: butler-db
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-phpmyadmin-volume
        target: /sessions
    ports:
      - 9001:80
    restart: always

volumes:
  butler-db-volume:
  butler-phpmyadmin-volume:

secrets:
  butler_db_root_password:
    file: .secrets/butler_db_root_password.txt

networks:
  butler-network: