version: '3.7'

services:
  butler-db:
    container_name: butler-db-main
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-release-butler
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  butler-db-volume:

networks:
  butler-network: