spring:
  application:
    name: Metal Release Butler
  groovy:
    template:
      check-template-location: false
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 5
      test-on-borrow: true
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop # (create, create-drop, validate, update)
    open-in-view: false
  cache:
    jcache:
      config: classpath:config/cache/ehcache.xml

server:
  port: 8095
  servlet:
    context-path: /metal-release-butler
  error:
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true

logging:
  config: classpath:config/logging/logback-spring.xml

httpclient:
  useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      url: .*
      metrics:
        tags:
          - key: URL
            expression: getRequestURI()
      rate-limits:
        - bandwidths:
            - capacity: 20
              time: 1
              unit: minutes
