spring:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

bucket4j:
  enabled: true

aws:
  bucket-name: rocks.metal-detector.s3.images

management:
  endpoints:
    web:
      base-path: ${ACTUATOR_BASE_PATH}
