spring:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

concurrency:
  release-import-pool-size: ${RELEASE_IMPORT_CORE_POOL_SIZE}

bucket4j:
  enabled: true

aws:
  bucket-name: preview.rocks.metal-detector.s3.images
