spring:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      url: .*
      metrics:
        tags:
          - key: URL
            expression: getRequestURI()
      rate-limits:
        - bandwidths:
            - capacity: 20
              time: 1
              unit: minutes
