openapi: 3.0.0
servers:
  - description: Metal Release Butler local test server
    url: http://localhost:8095
info:
  description: |
    The Metal Release Butler offers the following functionalities for upcoming releases of metal bands:

      - Query upcoming releases
      - Query upcoming releases for a defined period of time (also allows periods of time in the past)
      - Query upcoming releases for certain bands
      - Query upcoming releases for specific bands for a defined period of time (also allows periods of time in the past)

    The result set can be requested paginated for all queries.

  version: "1.0.0"
  title: Metal Release Butler
  # termsOfService: 'http://swagger.io/terms/'
  contact:
    email: wagner.daniel87@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: Upcoming Releases
    description: Query upcoming releases or all releases for a defined period of time (also allows periods of time in the past).
  - name: Upcoming Releases for certain bands
    description: Query upcoming releases for certain bands. You have the option of limiting the period to a date you specify.

paths:
  /metal-release-butler/rest/v1/releases/:
    get:
      tags:
        - Upcoming Releases
      # summary: short summary
      description: ...
      operationId: ...
      parameters:
        - name: page
          in: path # ToDo DanielW: Was ist das?
          description: ...
          required: false
          default: 1
          schema:
            type: integer
            format: int32
        - name: size
          in: path # ToDo DanielW: Was ist das?
          description: ...
          required: false
          default: 20
          schema:
            type: integer
            format: int32
        - name: from
          in: path # ToDo DanielW: Was ist das?
          description: ...
          required: false
          schema:
            type: string
            format: date
        - name: to
          in: path # ToDo DanielW: Was ist das?
          description: ...
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkingExperience'
            application/xml:
              schema:
                $ref: '#/components/schemas/WorkingExperience'
        '400':
          description: ID has an invalid format, for example could not be parsed into a long value
        '404':
          description: working experience resource for ID not found

  /metal-release-butler/rest/v1/releases/my-artists:
    post:
      tags:
        - Upcoming Releases for certain bands
      # summary: short summary
      description: Creates a single working experience
      requestBody:
        $ref: '#/components/requestBodies/WorkingExperience'
      responses:
        '201':
          description: resource was successfully created
        '400':
          description: create request is not valid

# externalDocs:
#   description: Find out more about Swagger
#  url: 'http://swagger.io'

components:
  schemas:
    WorkingExperience:
      type: object
      required:
        - company
        - begin
        - jobTitle
        - placeOfWork
      properties:
        company:
          type: string
          example: John Doe Company
        begin:
          type: string
          format: date
          example: '2015-10-01'
        end:
          type: string
          format: date
          example: '2019-12-31'
        jobTitle:
          type: string
          example: Java Developer
        placeOfWork:
          type: string
          example: Berlin
        focalPoints:
          type: array
          items:
            type: string
          example: [
            Development of the core product,
            Independent implementation and documentation of features and test cases as part of the SCRUM development team,
            Estimating Development Expenses,
          ]

  requestBodies:
    WorkingExperience:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WorkingExperience'
        application/xml:
          schema:
            $ref: '#/components/schemas/WorkingExperience'
      description: Working experience object that needs to be added
      required: true