[versions]
awsS3Sdk = "1.12.139"
commonsIo = "2.11.0"
flyway = "8.4.1"
groovy = "3.0.9"
httpClient = "4.5.13"
h2 = "1.4.200"
jackson = "2.13.1"
jsonwebtoken = "0.9.1"
jsoup = "1.14.3"
junit = "5.8.2"
micrometer = "1.8.2"
postgresql = "42.3.1"
spock = "2.0-groovy-3.0"
spring = "5.3.15"
springBoot = "2.6.2"
springSecurity = "5.6.1"
swagger = "3.0.0"
