[versions]
awsS3Sdk = "1.12.222"
commonsIo = "2.11.0"
flyway = "8.5.11"
groovy = "4.0.2"
httpClient = "4.5.13"
h2 = "2.1.212"
jackson = "2.13.3"
jsonwebtoken = "0.9.1"
jsoup = "1.15.1"
junit = "5.8.2"
micrometer = "1.9.0"
postgresql = "42.3.5"
spock = "2.2-M1-groovy-4.0"
spring = "5.3.20"
springBoot = "2.7.0"
springSecurity = "5.7.0"
swagger = "3.0.0"
