[versions]
awsS3Sdk = "1.12.65"
commonsIo = "2.11.0"
flyway = "7.14.1"
groovy = "3.0.9"
httpBuilder = "1.0.4"
httpClient = "4.5.13"
h2 = "1.4.200"
jsonwebtoken = "0.9.1"
jsoup = "1.14.2"
junit = "5.8.1"
micrometer = "1.7.4"
postgresql = "42.2.23"
spock = "2.0-groovy-3.0"
springBoot = "2.5.5"
springSecurity = "5.5.2"
swagger = "3.0.0"
