[versions]
awsS3Sdk = "1.12.109"
commonsIo = "2.11.0"
flyway = "8.0.4"
groovy = "3.0.9"
httpClient = "4.5.13"
h2 = "1.4.200"
jackson = "2.13.0"
jsonwebtoken = "0.9.1"
jsoup = "1.14.3"
junit = "5.8.1"
micrometer = "1.8.0"
postgresql = "42.3.1"
spock = "2.0-groovy-3.0"
spring = "5.3.13"
springBoot = "2.6.0"
springSecurity = "5.6.0"
swagger = "3.0.0"
