[versions]
awsS3Sdk = "1.12.280"
commonsIo = "2.11.0"
flyway = "8.5.13"
groovy = "4.0.4"
httpClient = "4.5.13"
h2 = "2.1.214"
jackson = "2.13.3"
jsonwebtoken = "0.9.1"
jsoup = "1.15.2"
junit = "5.9.0"
micrometer = "1.9.3"
postgresql = "42.4.2"
spock = "2.2-M3-groovy-4.0"
spring = "5.3.22"
springBoot = "2.7.3"
springSecurity = "5.7.3"
swagger = "3.0.0"
