[versions]
awsS3Sdk = "1.12.180"
commonsIo = "2.11.0"
flyway = "8.5.4"
groovy = "3.0.10"
httpClient = "4.5.13"
h2 = "2.1.210"
jackson = "2.13.2"
jsonwebtoken = "0.9.1"
jsoup = "1.14.3"
junit = "5.8.2"
micrometer = "1.8.4"
postgresql = "42.3.3"
spock = "2.1-groovy-3.0"
spring = "5.3.17"
springBoot = "2.6.4"
springSecurity = "5.6.2"
swagger = "3.0.0"
