spring:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8095
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

aws:
  bucket-name: dev.rocks.metal-detector.s3.images
