spring:
  application:
    name: Metal Release Butler
  autoconfigure: # prevents spring from showing default user password in logs on startup
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  groovy:
    template:
      check-template-location: false
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      max-lifetime: 2000000
      connectionTimeout: 30000
      idle-timeout: 30000
  sql:
    init:
      platform: postgres
      mode: always
  flyway:
    baseline-on-migrate: true
    sql-migration-prefix: v
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # (create, create-drop, validate, update)
    open-in-view: false
  cache:
    jcache:
      config: classpath:config/cache/ehcache.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-app:8080

server:
  port: 8095
  error:
    include-message: always
    include-binding-errors: never
    include-exception: false
  tomcat:
    accesslog:
      enabled: true
  shutdown: graceful

logging:
  config: classpath:config/logging/logback-spring.xml

httpclient:
  useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

concurrency:
  release-import-pool-size: 4

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3-host: https://s3.eu-central-1.amazonaws.com
  bucket-name:

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus, flyway
