spring:
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-app:8080

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

aws:
  bucket-name: rocks.metal-detector.s3.images

logging:
  config: classpath:config/logging/logback.xml

management:
  endpoints:
    web:
      path-mapping:
        info: ${ACTUATOR_INFO_PATH}
        metrics: ${ACTUATOR_METRICS_PATH}
        prometheus: ${ACTUATOR_PROMETHEUS_PATH}
        flyway: ${ACTUATOR_FLYWAY_PATH}
