name: Continous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Execute all tests
        run: ./gradlew clean test --no-daemon --info --stacktrace
