name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Generate coverage report
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.2
          arguments: jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-umbrella
          fail_ci_if_error: true
