name: Docker Image

on:
  push:
    branches: 
      - master

jobs:
  docker-image-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Execute gradle task 'bootJar'
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: clean bootJar
      - name: Build the Docker image
        run: docker build --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t metaldetector/metal-release-butler:latest .
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: metaldetector/metal-release-butler
          tags: latest
