name: Metal Release Butler Docker Image

on:
  push:
    branches: 
      - master

jobs:
  docker-image-build:
    name: build metal release butler docker image
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --no-cache=true --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t metalreleaseradar/metal-release-butler:latest .
