name: Docker Image

on:
  push:
    branches: 
      - master

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Execute gradle task 'build' and 'publish'
        run: ./gradlew clean build publish --no-daemon --info --stacktrace
